---
- block:
  - name: Import Grafana GPG signing key [Debian/Ubuntu]
    apt_key:
      url: "https://packagecloud.io/gpg.key"
      state: present
      validate_certs: false
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"

  - name: Add Grafana repository [Debian/Ubuntu]
    apt_repository:
      repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
      state: present

  - name: Install Grafana packages [Debian/Ubuntu]
    apt:
      name: grafana
      state: present
      update_cache: yes
      cache_valid_time: 3600
    notify: restart grafana
  when: grafana_install_url == None

- block:
  - name: Download Grafana package via URL [Debian/Ubuntu]
    become: no
    get_url:
      url: "{{ grafana_install_url }}"
      dest: "/tmp/grafana-ansible-download.deb"
      validate_certs: no
    run_once: true
    delegate_to: localhost

  - name: Propagate Grafana package [Debian/Ubuntu]
    copy:
      src: "/tmp/grafana-ansible-download.deb"
      dest: "/tmp/grafana-ansible-download.deb"

  - name: Install downloaded Grafana package [Debian/Ubuntu]
    apt:
      deb: /tmp/grafana-ansible-download.deb
      state: present
    notify: restart grafana
  when: grafana_install_url != None
