- name: Check if datasources are configured when dashboards are set to be installed
  fail:
    msg: "You need to specify datasources for dashboards!!!"
  when: grafana_dashboards != [] and grafana_datasources == []

- name: Check if grafana admin password is set
  fail:
    msg: "Please specify grafana admin password (grafana_security.admin_password)"
  when: grafana_security.admin_password == ''

- name: Check if all variables in datasources definition have their correct type
  fail:
    msg: "Boolean variables in grafana_datasources shouldn't be passed as strings. Please remove unneded apostrophes."
  when: ( item.isDefault is defined and item.isDefault is string ) or
        ( item.basicAuth is defined and item.basicAuth is string )
  with_items: "{{ grafana_datasources }}"
